name: Build and Test

on:
  push:
    tags:
      - v*
    branches: 
      - main
  pull_request:
    branches: 
      - main
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'

    - name: Build
      run: |
           go mod tidy
           go build -v ./...

    - name: Test
      run: |
           go test -v ./...
           go test ./... -coverprofile coverage.out -covermode count
           go tool cover -func coverage.out

    - name: Go Coverage Badge  # Pass the `coverage.out` output to this action
      uses: tj-actions/coverage-badge-go@v2
      with:
       filename: coverage.out       

    - name: Test coverage
      env:
          TESTCOVERAGE_THRESHOLD: 0
      run: |
            echo "Test Coverage."
            echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
            totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
            echo "Current test coverage : $totalCoverage %"
            if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 >= $2)}') )); then
                echo "OK"
            else
                echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
                echo "Failed"
                exit 1
            fi
